title: 👋 EMNLP Attendees!
logo: assets/img/profile.jpg
email: jaewooklee@cs.umass.edu
# description: I am Jake, a CS Ph.D. student @UMass Amherst focused on applying LLMs to solve real-world problems.
description: |
  Hey there! I'm Jake, a passionate CS Ph.D. student @UMass Amherst, diving deep into the potential of large language models to tackle real-world challenges.
  *I'm on the lookout for an exciting research internship opportunity for summer 2025—let's work together to push the boundaries of what's possible with LLMs!*
favicon: true
theme: jekyll-theme-minimal
# github:
#   is_project_page: false

navigation:
  - name: home
    link: ./index.html
  - name: EMNLP2024
    link: ./emnlp2024.html
    
platforms:
  # - name: GitHub
  #   icon: <i class="fa-brands fa-github"></i>
  #   link: https://github.com/vaibhavvikas
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/jaewook-lee-67791918b/
    
# Site Author
author:
  name             : "Jaewook Lee"
  avatar           : "/assets/images/profile.jpg"
  bio              : "<i>Applying,<br>NLP,<br> for education.</i>"
  location         :
  email            : 
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:jaewooklee@umass.edu
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/chriskhanhtran"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jaewook-lee-67791918b/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/LeeJaewookJake"
    # - label: "YouTube"
      # icon: "fab fa-fw fa-youtube"
      # url: https://www.youtube.com/channel/UCo8okHIdSppn_idUVuuebhg
    # sublist:
    #   - name: Human Evaluation Critera
    #     link: ./#Criteria
  # - name: Another Page
  #   link: ./another-page.html
  # - ...
# # Site Footer
# footer:
#   links:
#     - label: "Email"
#       icon: "fas fa-fw fa-envelope-square"
#       url: mailto:jaewooklee@umass.edu
#     - label: "LinkedIn"
#       icon: "fab fa-fw fa-linkedin"
#       url: "https://www.linkedin.com/in/jaewook-lee-67791918b/"
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://x.com/LeeJaewookJake"
      
